'use strict';
(function () {
  window.globalValues = {
    ENTER_KEYCODE: 13,
    ESC_KEYCODE: 27,
    MAX_AMOUNT_OF_PINS: 5,
    DEBOUNCE_INTERVAL: 500,
    SUCCESSFUL_HTTP_CODE: 200,
    SERVER_TIMEOUT: 10000,
    CENTER_OF_PIN: 33,
    DISTANCE_X_TO_SHARP_POINT_OF_PIN: 72,
    DISTANCE_Y_TO_SHARP_POINT_OF_PIN: 32,
    MAX_Y_PIN_POSITION: 630,
    MIN_Y_PIN_POSITION: 130,
    MIN_X_PIN_POSITION: 0,
    MAX_X_PIN_POSITION: 1140
  };
})();
